# Generated by Django 5.1 on 2024-09-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('auth_password', models.CharField(max_length=20)),
                ('is_auth', models.BooleanField()),
            ],
        ),
    ]
