# Generated by Django 5.1 on 2024-09-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='auth_password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
    ]
