# Generated by Django 5.1 on 2024-09-21 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_account_auth_password_alter_account_is_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
