# Generated by Django 5.1 on 2024-09-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_account_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
